# Start from the base Ubuntu image
FROM ubuntu:latest

# Label it, if you're into that sort of thing
LABEL maintainer="<E-Mail>"
LABEL version="1.0"

# Set environment variables to non-interactive
ENV DEBIAN_FRONTEND=non-interactive

# Run package updates and install packages
RUN apt-get update \
    && apt-get install -y \
    curl \
    wget \
    software-properties-common \
    python3 \
    python3-pip \
    vim

RUN mkdir -p /data/code

# Install code-server
RUN curl -fsSL https://code-server.dev/install.sh | sh

RUN code-server --install-extension bmewburn.vscode-intelephense-client
RUN code-server --install-extension CoenraadS.bracket-pair-colorizer
RUN code-server --install-extension ecmel.vscode-html-css
RUN code-server --install-extension enkia.tokyo-night
RUN code-server --install-extension esbenp.prettier-vscode
RUN code-server --install-extension jgclark.vscode-todo-highlight
RUN code-server --install-extension ms-python.pylint
RUN code-server --install-extension ms-python.python
RUN code-server --install-extension ms-toolsai.jupyter
RUN code-server --install-extension yandeu.five-server
RUN code-server --install-extension vscodevim.vim

# Set up the entry point
ENTRYPOINT ["code-server", "--bind-addr", "0.0.0.0:8080", "--auth", "none"]

# Expose the code-server port
EXPOSE 8080
